✨ Authentication with LDAP
penpot/penpot pull request #285
Opened 2020-07-24 16:18 UTC by wizzytod

Users can sign in/sign up with LDAP credentials using the same login form.

![Sign in with LDAP](https://user-images.githubusercontent.com/9740575/88412497-56283500-cde2-11ea-8263-721e01e3e047.gif)

2020-07-24 16:31 UTC, niwinz commented
as a quick view, very nice job

2020-07-25 23:14 UTC, madmath03 requested changes
A few questions for you @wizzytod , but overall great work.

I'm gonna send an update of the management guide documentation to complete this.

2020-07-25 23:14 UTC, madmath03 commented on backend/deps.edn
> +  org.clojars.pntblnk/clj-ldap {:mvn/version"0.0.16"}
@wizzytod should we use [puppetlabs/clj-ldap](https://github.com/puppetlabs/clj-ldap) instead ?

I see that [pntblnk/clj-ldap](https://github.com/pauldorman/clj-ldap) has not be updated for 3 years, but Puppet forked it and updates quite recently.
Might be safer for the long term. I let you check and validate if switch is possible.

2020-07-25 23:14 UTC, madmath03 commented on backend/src/uxbox/config.clj
> +   ;:ldap-auth-avatar-attribute "jpegPhoto"
I think we can safely set default values like query and attributes that would match most cases.

```suggestion
   :debug-humanize-transit true

   ;; LDAP auth disabled by default. Set ldap-auth-host to enable
   ;:ldap-auth-host "ldap.mysupercompany.com"
   ;:ldap-auth-port 389
   :ldap-auth-version "3"
   ;:ldap-bind-dn "cn=admin,dc=ldap,dc=mysupercompany,dc=com"
   ;:ldap-bind-password "verysecure"
   ;:ldap-auth-ssl false
   ;:ldap-auth-starttls false
   ;:ldap-auth-base-dn "ou=People,dc=ldap,dc=mysupercompany,dc=com"
   :ldap-auth-user-query "(|(uid=$username)(mail=$username))"
   :ldap-auth-username-attribute "uid"
   :ldap-auth-email-attribute "mail"
   :ldap-auth-fullname-attribute "displayName"
   :ldap-auth-avatar-attribute "jpegPhoto"})
```

2020-07-25 23:14 UTC, madmath03 commented on backend/src/uxbox/config.clj
> +(s/def ::ldap-auth-version ::us/string)
I see that `clj-ldap` does not support configuration of LDAP version, so we can remove `ldap-auth-version`.
```suggestion
```

2020-07-25 23:14 UTC, madmath03 commented on frontend/resources/locales.json
> +      "es" : "",
```suggestion
      "fr" : "Se connecter via LDAP",
      "es" : "Entrar con LDAP",
```

2020-07-28 10:45 UTC, wizzytod commented on backend/deps.edn
> +  org.clojars.pntblnk/clj-ldap {:mvn/version"0.0.16"}
I agree, adopted code to slightly different API. thanks!

2020-08-05 14:24 UTC, niwinz commented
Is this ready to merge?

2020-08-05 14:27 UTC, niwinz commented
Additionally, would be awesome to have a concrete (and if possible easy/simple) instructions to test this. Maybe a docker container on the devenv with ldap provider with default data or something similar.

2020-08-05 14:27 UTC, madmath03 commented
> Is this ready to merge?

Unless you see anything wrong during review, then yes it's ready to be merged.

2020-08-05 15:18 UTC, madmath03 commented
> Additionally, would be awesome to have a concrete (and if possible easy/simple) instructions to test this. Maybe a docker container on the devenv with ldap provider with default data or something similar.

Would be nice indeed, but might take some time to get a local OpenLDAP working (it can easily get tricky to configure).
We will have a look to what we can do for that.

2020-08-05 15:45 UTC, niwinz commented
Not worry, this is not blocking for merge this, but in order to be able to maintain this without accidental breaking, we need a way check that integration works. 

Honestly, I know nothing about LDAP, so right now i can only review the code but can't test it. If in a future release we change something in the auth subsystem, without a test enviroment for ldap we can leave accidentally the LDAP broken until some user that uses it detects the fail...

2020-08-10 08:55 UTC, niwinz commented
Merged manually

2020-08-10 08:55 UTC, closed without merging