✨ Authentication with Gitlab
penpot/penpot pull request #303
Opened 2020-08-24 10:30 UTC by wizzytod

Users can sign in/sign up with Gitlab OAuth2 provider.
![Login with gitlab](https://user-images.githubusercontent.com/9740575/91034547-d6be9900-e60d-11ea-8d5d-c1520b82ec2f.gif)

2020-08-24 11:02 UTC, madmath03 requested changes

2020-08-24 11:02 UTC, madmath03 commented on backend/src/app/http/auth/gitlab.clj
> +        (log/error "unexpected error on parsing response body from gitlab access tooken request" e)
Small typo, present in Google auth as well.
```suggestion
        (log/error "unexpected error on parsing response body from gitlab access token request" e)
```

2020-08-24 11:02 UTC, madmath03 commented on backend/src/app/http/auth/gitlab.clj
> +        (log/error "unexpected error on parsing response body from gitlab access tooken request" e)
Small typo, present in Google auth as well.
```suggestion
        (log/error "unexpected error on parsing response body from gitlab access token request" e)
```

2020-08-24 11:18 UTC, madmath03 approved these changes
Great work @wizzytod , this looks awesome!

2020-09-07 07:52 UTC, niwinz approved these changes
:heart:

2020-09-07 07:52 UTC, merged