:lipstick: New UI for Swap Component
penpot/penpot pull request #3787
Opened 2023-11-09 18:22 UTC by pabloalba

Implements https://tree.taiga.io/project/penpot/task/6055

2023-11-13 12:30 UTC, EvaMarco requested changes
Change color defs and rems please :)

2023-11-13 12:30 UTC, EvaMarco commented on frontend/src/app/main/ui/workspace/sidebar/options/menus/component.cljs
> +     [:div
Is this div neccessary?

2023-11-13 12:30 UTC, EvaMarco commented on frontend/src/app/main/ui/workspace/sidebar/options/menus/component.cljs
> +                  :on-click #(when can-swap? (st/emit! (dwsp/open-specialized-panel :component-swap shapes)))}
Is better to define on-click functions on let instead of inline

2023-11-13 12:30 UTC, EvaMarco commented on frontend/src/app/main/ui/workspace/sidebar/options/menus/component.scss
> +            stroke: var(--color-gray-20);
Don't use color defs directly, create a desing token fot it, then use that design token

2023-11-13 12:30 UTC, EvaMarco commented on frontend/src/app/main/ui/workspace/sidebar/options/menus/component.scss
> +          color: var(--color-gray-40);
Same

2023-11-13 12:30 UTC, EvaMarco commented on frontend/src/app/main/ui/workspace/sidebar/options/menus/component.scss
> +      fill: var(--color-gray-20);
Same

2023-11-13 12:30 UTC, EvaMarco commented on frontend/src/app/main/ui/workspace/sidebar/options/menus/component.scss
> +      margin-right: 1rem;
Use spacing variables ($s-16) in this case

2023-11-13 12:30 UTC, EvaMarco commented on frontend/src/app/main/ui/workspace/sidebar/options/menus/component.scss
> +      height: 0.7rem;
Dont use rem

2023-11-13 12:30 UTC, EvaMarco commented on frontend/src/app/main/ui/workspace/sidebar/options/menus/component.scss
> +      stroke: var(--color-gray-20);
create design token

2023-11-13 12:30 UTC, EvaMarco commented on frontend/src/app/main/ui/workspace/sidebar/options/menus/component.scss
> +      background-color: var(--color-background-tertiary);
Create design-token

2023-11-13 12:30 UTC, EvaMarco commented on frontend/src/app/main/ui/workspace/sidebar/options/menus/component.scss
> +            color: var(--color-foreground-secondary);
same

2023-11-13 12:30 UTC, EvaMarco commented on frontend/src/app/main/ui/workspace/sidebar/options/menus/component.scss
> +          color: var(--color-foreground-primary);
same

2023-11-13 12:30 UTC, EvaMarco commented on frontend/src/app/main/ui/workspace/sidebar/options/menus/component.scss
> +            border-color: var(--color-accent-primary-muted);
same

2023-11-13 12:30 UTC, EvaMarco commented on frontend/src/app/main/ui/workspace/sidebar/options/menus/component.scss
> +        fill: var(--color-gray-20);
same

2023-11-13 12:30 UTC, EvaMarco commented on frontend/src/app/main/ui/workspace/sidebar/options/menus/component.scss
> +        margin-right: 1rem;
don't use rem

2023-11-13 12:30 UTC, EvaMarco commented on frontend/src/app/main/ui/workspace/sidebar/options/menus/component.scss
> +        background-color: var(--dark-gray-3);
same

2023-11-13 12:30 UTC, EvaMarco commented on frontend/src/app/main/ui/workspace/sidebar/options/menus/component.scss
> +          color: var(--color-primary);
same

2023-11-14 09:42 UTC, pabloalba commented on frontend/src/app/main/ui/workspace/sidebar/options/menus/component.cljs
> +     [:div
I think so, for the space-between for the name and the icon

2023-11-14 10:57 UTC, EvaMarco approved these changes

2023-11-14 10:57 UTC, merged