✨ Authentication with Github
penpot/penpot pull request #394
Opened 2020-11-20 11:39 UTC by wizzytod

Users can sign in/sign up with Gitlab OAuth2 provider.

2020-11-20 11:40 UTC, wizzytod commented
@madmath03 Please check this out if I miss something! Thanks!

2020-11-23 11:31 UTC, madmath03 requested changes
Just a small typo in Russian translation, otherwise looks very good!

2020-11-23 11:31 UTC, madmath03 commented on frontend/resources/locales.json
> +      "ru" : "Вход через Gitnub",
```suggestion
      "ru" : "Вход через Github",
```

2020-11-26 13:13 UTC, niwinz commented
This is still wip?, ping me when it is ready for take a quick look and merge!
BTW nice work.

2020-12-28 10:45 UTC, wizzytod commented
@niwinz please take a look! It is ready to merge now)

2020-12-28 10:57 UTC, niwinz commented
Nice!, Thanks!

2021-01-06 10:57 UTC, niwinz commented
I have merged this MR with my other branch where i working, and is pending to be merged the next days: #441

2021-01-06 10:57 UTC, closed without merging